// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(AabDbContext))]
    [Migration("20210404135103_Avatar")]
    partial class Avatar
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("Data.Entity.Approval.ApprovalTableEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("CreatorTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifyTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LastModifyUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("OwnerOrganizeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("DeleteUserId");

                    b.HasIndex("LastModifyUserId");

                    b.HasIndex("OwnerOrganizeId");

                    b.ToTable("ApprovalTableEntity");
                });

            modelBuilder.Entity("Data.Entity.Approval.InfoClassEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("CreatorTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int");

                    b.Property<int>("ExpiredMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifyTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LastModifyUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("DeleteUserId");

                    b.HasIndex("LastModifyUserId");

                    b.ToTable("InfoClassEntity");
                });

            modelBuilder.Entity("Data.Entity.Approval.InfoGroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ApprovalTableEntityId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatorTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifyTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LastModifyUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalTableEntityId");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("DeleteUserId");

                    b.HasIndex("LastModifyUserId");

                    b.ToTable("InfoGroupEntity");
                });

            modelBuilder.Entity("Data.Entity.Approval.InfoGroupItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatorTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifyTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LastModifyUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("DeleteUserId");

                    b.HasIndex("GroupId");

                    b.HasIndex("ItemId");

                    b.HasIndex("LastModifyUserId");

                    b.ToTable("InfoGroupItemEntity");
                });

            modelBuilder.Entity("Data.Entity.Business.ApprovalInstanceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AppprovalTableId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatorTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("LastModifyTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LastModifyUserId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppprovalTableId");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("DeleteUserId");

                    b.HasIndex("LastModifyUserId");

                    b.HasIndex("UserId");

                    b.ToTable("ApprovalInstanceEntity");
                });

            modelBuilder.Entity("Data.Entity.Business.InfoInstanceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ApprovalInstanceEntityId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatorTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int");

                    b.Property<int?>("InfoClassId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifyTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LastModifyUserId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalInstanceEntityId");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("DeleteUserId");

                    b.HasIndex("InfoClassId");

                    b.HasIndex("LastModifyUserId");

                    b.HasIndex("UserId");

                    b.ToTable("InfoInstanceEntity");
                });

            modelBuilder.Entity("Data.Entity.SystemManage.MenuEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BasePath")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("CreatorTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("LastModifyTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LastModifyUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int?>("Target")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("DeleteUserId");

                    b.HasIndex("LastModifyUserId");

                    b.HasIndex("ParentId");

                    b.ToTable("MenuEntity");
                });

            modelBuilder.Entity("Data.Entity.SystemManage.OrganizeCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatorTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifyTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LastModifyUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("DeleteUserId");

                    b.HasIndex("LastModifyUserId");

                    b.ToTable("OrganizeCategoryEntity");
                });

            modelBuilder.Entity("Data.Entity.SystemManage.OrganizeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatorTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifyTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LastModifyUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("DeleteUserId");

                    b.HasIndex("LastModifyUserId");

                    b.HasIndex("ParentId");

                    b.ToTable("OrganizeEntity");
                });

            modelBuilder.Entity("Data.Entity.SystemManage.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatorTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("LastModifyTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LastModifyUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("OrganizeCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("OrganizeDutyLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("DeleteUserId");

                    b.HasIndex("LastModifyUserId");

                    b.HasIndex("OrganizeCategoryId");

                    b.ToTable("RoleEntity");
                });

            modelBuilder.Entity("Data.Entity.SystemManage.RoleMenuEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatorTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifyTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LastModifyUserId")
                        .HasColumnType("int");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("DeleteUserId");

                    b.HasIndex("LastModifyUserId");

                    b.HasIndex("MenuId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleMenuEntity");
                });

            modelBuilder.Entity("Data.Entity.SystemManage.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Contract")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("CreatorTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int");

                    b.Property<bool?>("EnabledMark")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsAdministrator")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifyTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LastModifyUserId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("DeleteUserId");

                    b.HasIndex("LastModifyUserId");

                    b.ToTable("UserEntity");
                });

            modelBuilder.Entity("Data.Entity.SystemManage.UserOrganizeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatorTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int");

                    b.Property<int>("DutyLevel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifyTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LastModifyUserId")
                        .HasColumnType("int");

                    b.Property<int>("OrganizeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("DeleteUserId");

                    b.HasIndex("LastModifyUserId");

                    b.HasIndex("OrganizeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserOrganizeEntity");
                });

            modelBuilder.Entity("Data.Entity.SystemSecurity.DbBackupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("BackupTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BackupType")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("CreatorTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<string>("DbName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FileSize")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("LastModifyTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LastModifyUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("DeleteUserId");

                    b.HasIndex("LastModifyUserId");

                    b.ToTable("DbBackupEntity");
                });

            modelBuilder.Entity("Data.Entity.SystemSecurity.LogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatorTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("LastModifyTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LastModifyUserId")
                        .HasColumnType("int");

                    b.Property<bool?>("Result")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("DeleteUserId");

                    b.HasIndex("LastModifyUserId");

                    b.ToTable("LogEntity");
                });

            modelBuilder.Entity("Data.Entity.Approval.ApprovalTableEntity", b =>
                {
                    b.HasOne("Data.Entity.SystemManage.UserEntity", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "LastModifyUser")
                        .WithMany()
                        .HasForeignKey("LastModifyUserId");

                    b.HasOne("Data.Entity.SystemManage.OrganizeEntity", "OwnerOrganize")
                        .WithMany("ApprovalTables")
                        .HasForeignKey("OwnerOrganizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatorUser");

                    b.Navigation("DeleteUser");

                    b.Navigation("LastModifyUser");

                    b.Navigation("OwnerOrganize");
                });

            modelBuilder.Entity("Data.Entity.Approval.InfoClassEntity", b =>
                {
                    b.HasOne("Data.Entity.SystemManage.UserEntity", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "LastModifyUser")
                        .WithMany()
                        .HasForeignKey("LastModifyUserId");

                    b.Navigation("CreatorUser");

                    b.Navigation("DeleteUser");

                    b.Navigation("LastModifyUser");
                });

            modelBuilder.Entity("Data.Entity.Approval.InfoGroupEntity", b =>
                {
                    b.HasOne("Data.Entity.Approval.ApprovalTableEntity", null)
                        .WithMany("InfoGroups")
                        .HasForeignKey("ApprovalTableEntityId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "LastModifyUser")
                        .WithMany()
                        .HasForeignKey("LastModifyUserId");

                    b.Navigation("CreatorUser");

                    b.Navigation("DeleteUser");

                    b.Navigation("LastModifyUser");
                });

            modelBuilder.Entity("Data.Entity.Approval.InfoGroupItemEntity", b =>
                {
                    b.HasOne("Data.Entity.SystemManage.UserEntity", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId");

                    b.HasOne("Data.Entity.Approval.InfoGroupEntity", "Group")
                        .WithMany("Items")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entity.Approval.InfoClassEntity", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "LastModifyUser")
                        .WithMany()
                        .HasForeignKey("LastModifyUserId");

                    b.Navigation("CreatorUser");

                    b.Navigation("DeleteUser");

                    b.Navigation("Group");

                    b.Navigation("Item");

                    b.Navigation("LastModifyUser");
                });

            modelBuilder.Entity("Data.Entity.Business.ApprovalInstanceEntity", b =>
                {
                    b.HasOne("Data.Entity.Approval.ApprovalTableEntity", "AppprovalTable")
                        .WithMany()
                        .HasForeignKey("AppprovalTableId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "LastModifyUser")
                        .WithMany()
                        .HasForeignKey("LastModifyUserId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("AppprovalTable");

                    b.Navigation("CreatorUser");

                    b.Navigation("DeleteUser");

                    b.Navigation("LastModifyUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Entity.Business.InfoInstanceEntity", b =>
                {
                    b.HasOne("Data.Entity.Business.ApprovalInstanceEntity", null)
                        .WithMany("InfoInstances")
                        .HasForeignKey("ApprovalInstanceEntityId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId");

                    b.HasOne("Data.Entity.Approval.InfoClassEntity", "InfoClass")
                        .WithMany()
                        .HasForeignKey("InfoClassId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "LastModifyUser")
                        .WithMany()
                        .HasForeignKey("LastModifyUserId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "User")
                        .WithMany("InfoInstances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatorUser");

                    b.Navigation("DeleteUser");

                    b.Navigation("InfoClass");

                    b.Navigation("LastModifyUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Entity.SystemManage.MenuEntity", b =>
                {
                    b.HasOne("Data.Entity.SystemManage.UserEntity", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "LastModifyUser")
                        .WithMany()
                        .HasForeignKey("LastModifyUserId");

                    b.HasOne("Data.Entity.SystemManage.MenuEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("CreatorUser");

                    b.Navigation("DeleteUser");

                    b.Navigation("LastModifyUser");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Data.Entity.SystemManage.OrganizeCategoryEntity", b =>
                {
                    b.HasOne("Data.Entity.SystemManage.UserEntity", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "LastModifyUser")
                        .WithMany()
                        .HasForeignKey("LastModifyUserId");

                    b.Navigation("CreatorUser");

                    b.Navigation("DeleteUser");

                    b.Navigation("LastModifyUser");
                });

            modelBuilder.Entity("Data.Entity.SystemManage.OrganizeEntity", b =>
                {
                    b.HasOne("Data.Entity.SystemManage.OrganizeCategoryEntity", "Category")
                        .WithMany("Organizes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "LastModifyUser")
                        .WithMany()
                        .HasForeignKey("LastModifyUserId");

                    b.HasOne("Data.Entity.SystemManage.OrganizeEntity", "Parent")
                        .WithMany("SubOrganizes")
                        .HasForeignKey("ParentId");

                    b.Navigation("Category");

                    b.Navigation("CreatorUser");

                    b.Navigation("DeleteUser");

                    b.Navigation("LastModifyUser");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Data.Entity.SystemManage.RoleEntity", b =>
                {
                    b.HasOne("Data.Entity.SystemManage.UserEntity", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "LastModifyUser")
                        .WithMany()
                        .HasForeignKey("LastModifyUserId");

                    b.HasOne("Data.Entity.SystemManage.OrganizeCategoryEntity", "OrganizeCategory")
                        .WithMany()
                        .HasForeignKey("OrganizeCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatorUser");

                    b.Navigation("DeleteUser");

                    b.Navigation("LastModifyUser");

                    b.Navigation("OrganizeCategory");
                });

            modelBuilder.Entity("Data.Entity.SystemManage.RoleMenuEntity", b =>
                {
                    b.HasOne("Data.Entity.SystemManage.UserEntity", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "LastModifyUser")
                        .WithMany()
                        .HasForeignKey("LastModifyUserId");

                    b.HasOne("Data.Entity.SystemManage.MenuEntity", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entity.SystemManage.RoleEntity", "Role")
                        .WithMany("AvailableMenus")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatorUser");

                    b.Navigation("DeleteUser");

                    b.Navigation("LastModifyUser");

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Data.Entity.SystemManage.UserEntity", b =>
                {
                    b.HasOne("Data.Entity.SystemManage.UserEntity", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "LastModifyUser")
                        .WithMany()
                        .HasForeignKey("LastModifyUserId");

                    b.Navigation("CreatorUser");

                    b.Navigation("DeleteUser");

                    b.Navigation("LastModifyUser");
                });

            modelBuilder.Entity("Data.Entity.SystemManage.UserOrganizeEntity", b =>
                {
                    b.HasOne("Data.Entity.SystemManage.UserEntity", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "LastModifyUser")
                        .WithMany()
                        .HasForeignKey("LastModifyUserId");

                    b.HasOne("Data.Entity.SystemManage.OrganizeEntity", "Organize")
                        .WithMany("Users")
                        .HasForeignKey("OrganizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "User")
                        .WithMany("Organizes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatorUser");

                    b.Navigation("DeleteUser");

                    b.Navigation("LastModifyUser");

                    b.Navigation("Organize");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Entity.SystemSecurity.DbBackupEntity", b =>
                {
                    b.HasOne("Data.Entity.SystemManage.UserEntity", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "LastModifyUser")
                        .WithMany()
                        .HasForeignKey("LastModifyUserId");

                    b.Navigation("CreatorUser");

                    b.Navigation("DeleteUser");

                    b.Navigation("LastModifyUser");
                });

            modelBuilder.Entity("Data.Entity.SystemSecurity.LogEntity", b =>
                {
                    b.HasOne("Data.Entity.SystemManage.UserEntity", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId");

                    b.HasOne("Data.Entity.SystemManage.UserEntity", "LastModifyUser")
                        .WithMany()
                        .HasForeignKey("LastModifyUserId");

                    b.Navigation("CreatorUser");

                    b.Navigation("DeleteUser");

                    b.Navigation("LastModifyUser");
                });

            modelBuilder.Entity("Data.Entity.Approval.ApprovalTableEntity", b =>
                {
                    b.Navigation("InfoGroups");
                });

            modelBuilder.Entity("Data.Entity.Approval.InfoGroupEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Data.Entity.Business.ApprovalInstanceEntity", b =>
                {
                    b.Navigation("InfoInstances");
                });

            modelBuilder.Entity("Data.Entity.SystemManage.MenuEntity", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Data.Entity.SystemManage.OrganizeCategoryEntity", b =>
                {
                    b.Navigation("Organizes");
                });

            modelBuilder.Entity("Data.Entity.SystemManage.OrganizeEntity", b =>
                {
                    b.Navigation("ApprovalTables");

                    b.Navigation("SubOrganizes");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Data.Entity.SystemManage.RoleEntity", b =>
                {
                    b.Navigation("AvailableMenus");
                });

            modelBuilder.Entity("Data.Entity.SystemManage.UserEntity", b =>
                {
                    b.Navigation("InfoInstances");

                    b.Navigation("Organizes");
                });
#pragma warning restore 612, 618
        }
    }
}
